        
        <footer id="site-footer">
			
			<nav id="footer-nav"> 
				<ul>
					<li> <a href="">FAQ</a> </li>
					<li> <a href="">WTF</a> </li>
					<li> <a href="">LEGAL</a> </li>
					<li> <a href="">CONTACT</a> </li>
				</ul>
			</nav>
			
			<nav id="social-nav">
				<ul>
					<li> <a href="http://mailchimp.com/">SUBSCRIBE</a> </li>
					<li> <a href="http://twitter.com/thrillderness"><span class="icon-twitter"></span></a> </li>
					<li> <a href="http://instagram.com/thrillderness"><span class="icon-instagram"></span></a> </li>
					<li> <a href="http://facebook.com/thrillderness"><span class="icon-facebook"></span></a> </li>
					<li> <a href="http://thrillderness.org/feed"><span class="icon-rss"></span></a> </li>
				</ul>
			</nav>
			
			<!-- <hr /> -->
			<section>
				<h1 class="arrow"> <span class="icon-up"></span> <br /> </h1>
				<h2 class="wordmark"> <span class="icon-Thrillderness"></span> </h2>	
				<h2 class="tagline">Reviving endangered knowledge. Building a community. Having a blast.</h2>
	            <p  class="copyright"> &copy;2015 All rights reserved. </p>
			</section>
			
        
		</footer>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
