		<script src="//use.typekit.net/jlv0gcd.js"></script>
		<script>try{Typekit.load();}catch(e){}</script>
		<link rel="stylesheet" href="http://i.icomoon.io/public/temp/961fab5e9a/Thrillderness/style.css">
        <link rel="stylesheet" href="css/main.css"> <!-- Advanced & Browser Dependent -->

   </head>
        <body>

        <header id="site-header">
        	<a href="index" id="logo">
        		<!-- <strong>Thrillderness</strong> -->
				<span class="icon-Thrillderness"> </span>
        	</a>
			<nav id="primary">
        		<ul> 
					<li> <a href="#menu-primary" id="toggle-menu-primary"> <span class="icon-menu"> </span> Topics </a> </li>
					<li> <a href="about"> About </a> </li>
					<!-- <li> <a href="shop"> Shop </a> </li> -->
					<li> <a href="contact"> Contact </a> </li>
				</ul>
			</nav>
			<a href="#" id="toggle-search-primary">
				 <span class="icon-search"> </span>
			</a>
		</header>
		
		<div id="menu-primary">
			<nav id="categories">
				<ul>
					<li> <a href="">Talkin&rsquo; </a> </li>
					<li> <a href="">Adventure Log </a> </li>
					<li> <a href="">From the Shelf </a> </li>
					<li> <a href="">Daily Thrill </a> </li>
					<li> <a href="">Pack Lists </a> </li>
				</ul>
			</nav>
			<nav id="tags">
				<ul>
					<li> <a href=""> Bikepacking </a> </li>
					<li> <a href=""> Mountaineering </a> </li>
					<li> <a href=""> Trad Climbing </a> </li>
					<li> <a href=""> Trail Running </a> </li>
					<li> <a href=""> Sick Rigs </a> </li>
				</ul>
			</nav>
		</div>
		
		
		<div id="search-primary"> 
		     <?php include_once'inc/searchform.inc' ?>
		</div>